# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-13 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=1, max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=1, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='sula.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TotalLeche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalLeche', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='notaentrega',
            name='cantidad',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notaentrega',
            name='precio',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
